spring.application.name=fsad-skill-8

spring.jpa.hibernate.ddl-auto=update
spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/klus59
spring.datasource.username=root
spring.datasource.password=Lucky@630
spring.jpa.show-sql=true